package dev.abhay.hypericon.ui

import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.DialogProperties
import dev.abhay.hypericon.export.DownloadsSaver
import dev.abhay.hypericon.export.ThemeApplier
import dev.abhay.hypericon.model.IconStyle

private enum class StyleChoice(val label: String, val styles: Set<IconStyle>) {
    LIGHT("Light", setOf(IconStyle.LIGHT)),
    DARK("Dark", setOf(IconStyle.DARK)),
    BOTH("Both", setOf(IconStyle.LIGHT, IconStyle.DARK)),
}

/** Export options: theme name, icon style(s) and whether generated icons are included. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportOptionsSheet(defaults: ExportOptions, onExport: (ExportOptions) -> Unit, onDismiss: () -> Unit) {
    var name by rememberSaveable { mutableStateOf(defaults.name) }
    var choice by rememberSaveable {
        mutableStateOf(if (defaults.styles == setOf(IconStyle.DARK)) StyleChoice.DARK else StyleChoice.LIGHT)
    }
    var includeGenerated by rememberSaveable { mutableStateOf(defaults.includeGenerated) }

    ModalBottomSheet(onDismissRequest = onDismiss, sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)) {
        Column(Modifier.fillMaxWidth().padding(horizontal = 24.dp).padding(bottom = 24.dp)) {
            Text("Export theme", style = MaterialTheme.typography.titleLarge)
            Spacer(Modifier.height(16.dp))
            OutlinedTextField(
                value = name,
                onValueChange = { name = it },
                label = { Text("Theme name") },
                supportingText = { Text("\"· Light\" or \"· Dark\" is added") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(8.dp))
            Text("Icon style", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                StyleChoice.entries.forEachIndexed { index, option ->
                    SegmentedButton(
                        selected = choice == option,
                        onClick = { choice = option },
                        shape = SegmentedButtonDefaults.itemShape(index, StyleChoice.entries.size),
                    ) { Text(option.label) }
                }
            }
            if (choice == StyleChoice.BOTH) {
                Text(
                    "Creates two themes, one per style.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(top = 6.dp),
                )
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text("Include generated icons", style = MaterialTheme.typography.bodyLarge)
                    Text(
                        "Off: apps without their own monochrome icon keep their original icon.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                Spacer(Modifier.width(12.dp))
                Switch(checked = includeGenerated, onCheckedChange = { includeGenerated = it })
            }
            Spacer(Modifier.height(20.dp))
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                TextButton(onClick = onDismiss) { Text("Cancel") }
                Spacer(Modifier.width(8.dp))
                Button(onClick = { onExport(ExportOptions(name, choice.styles, includeGenerated)) }) { Text("Export") }
            }
        }
    }
}

/** Progress, result and error UI for exporting a theme. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportDialogs(
    state: ExportState,
    onCancel: () -> Unit,
    onDismiss: () -> Unit,
    onSaveCopy: (ExportedFile, String, (Boolean) -> Unit) -> Unit,
    /** Apply icons was started for this file (it becomes the Reapply target). */
    onApplied: (ExportedFile) -> Unit = {},
) {
    val context = LocalContext.current
    var saving by remember { mutableStateOf<ExportedFile?>(null) }
    val saveAs = rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument(DownloadsSaver.MIME_TYPE)) { uri ->
        val file = saving
        saving = null
        if (uri != null && file != null) {
            onSaveCopy(file, uri.toString()) { ok ->
                Toast.makeText(context, if (ok) "Saved" else "Couldn't save the file", Toast.LENGTH_SHORT).show()
            }
        }
    }

    when (state) {
        ExportState.Idle -> Unit
        is ExportState.Running -> AlertDialog(
            onDismissRequest = {},
            properties = DialogProperties(dismissOnBackPress = false, dismissOnClickOutside = false),
            title = { Text(if (state.files > 1) "Exporting theme ${state.file} of ${state.files}" else "Exporting theme") },
            text = {
                Column {
                    Text("Rendering ${state.done} of ${state.total} icons…")
                    Spacer(Modifier.height(12.dp))
                    LinearProgressIndicator(
                        progress = { if (state.total == 0) 0f else state.done.toFloat() / state.total },
                        modifier = Modifier.fillMaxWidth(),
                    )
                }
            },
            confirmButton = {},
            dismissButton = { TextButton(onClick = onCancel) { Text("Cancel") } },
        )
        is ExportState.Done -> ModalBottomSheet(onDismissRequest = onDismiss) {
            Column(Modifier.fillMaxWidth().padding(horizontal = 24.dp).padding(bottom = 24.dp)) {
                Text(if (state.files.size > 1) "Themes exported" else "Theme exported", style = MaterialTheme.typography.titleLarge)
                Spacer(Modifier.height(4.dp))
                Text(
                    "Apply icons changes only the icons through Theme Manager; your wallpaper and other theme parts stay as they are. This may not work on every HyperOS build.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                state.files.forEach { file ->
                    Spacer(Modifier.height(12.dp))
                    HorizontalDivider()
                    Spacer(Modifier.height(12.dp))
                    Text(
                        "${if (file.style == IconStyle.DARK) "Dark" else "Light"} icons · ${file.iconCount} icons",
                        style = MaterialTheme.typography.titleMedium,
                    )
                    Text(file.location, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(onClick = {
                            if (ThemeApplier.apply(context, file.absolutePath)) {
                                onApplied(file)
                            } else {
                                Toast.makeText(context, "Theme Manager isn't available", Toast.LENGTH_SHORT).show()
                            }
                        }) { Text("Apply icons") }
                        OutlinedButton(onClick = {
                            saving = file
                            saveAs.launch(file.fileName)
                        }) { Text("Save as…") }
                        TextButton(onClick = { context.startActivity(DownloadsSaver.shareIntent(file.uri)) }) { Text("Share") }
                    }
                }
                Spacer(Modifier.height(16.dp))
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                    TextButton(onClick = onDismiss) { Text("Done") }
                }
            }
        }
        is ExportState.Failed -> AlertDialog(
            onDismissRequest = onDismiss,
            title = { Text("Export failed") },
            text = { Text(state.message) },
            confirmButton = { TextButton(onClick = onDismiss) { Text("OK") } },
        )
    }
}
