package dev.abhay.hypericon.ui

import android.app.DownloadManager
import android.content.Intent
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.DialogProperties
import dev.abhay.hypericon.export.DownloadsSaver
import dev.abhay.hypericon.export.ExportKind
import dev.abhay.hypericon.export.ExportState
import dev.abhay.hypericon.export.ExportedFile
import dev.abhay.hypericon.export.LauncherHints
import dev.abhay.hypericon.export.ThemeApplier
import dev.abhay.hypericon.model.IconStyle
import java.text.DateFormat
import java.util.Date

private enum class StyleChoice(val label: String, val styles: Set<IconStyle>) {
    LIGHT("Light", setOf(IconStyle.LIGHT)),
    DARK("Dark", setOf(IconStyle.DARK)),
    BOTH("Both", setOf(IconStyle.LIGHT, IconStyle.DARK)),
}

/**
 * Export options: the target (HyperOS theme or icon pack), the name, the theme's icon style(s)
 * and whether generated icons are included.
 *
 * @param hasThemeManager without Theme Manager the HyperOS option is disabled.
 * @param packNameWarning what to warn about for an icon-pack name (same name exported before).
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportOptionsSheet(
    defaults: ExportOptions,
    onExport: (ExportOptions) -> Unit,
    onDismiss: () -> Unit,
    hasThemeManager: Boolean = true,
    packNameWarning: (String) -> PackNameWarning? = { null },
) {
    var target by rememberSaveable { mutableStateOf(if (hasThemeManager) defaults.target else ExportTarget.ICON_PACK) }
    var name by rememberSaveable { mutableStateOf(defaults.name) }
    var choice by rememberSaveable {
        mutableStateOf(if (defaults.styles == setOf(IconStyle.DARK)) StyleChoice.DARK else StyleChoice.LIGHT)
    }
    // An icon pack has one style for every icon (no "Both"), and its full label is editable: it
    // starts as "<name> · Light/Dark" and follows the style while it's still the suggested one.
    var packStyle by rememberSaveable { mutableStateOf(if (defaults.styles == setOf(IconStyle.DARK)) IconStyle.DARK else IconStyle.LIGHT) }
    var packName by rememberSaveable { mutableStateOf(suggestedPackName(defaults.name, packStyle)) }
    var includeGenerated by rememberSaveable { mutableStateOf(defaults.includeGenerated) }
    val pack = target == ExportTarget.ICON_PACK
    val warning = if (pack) remember(packName) { packNameWarning(packName) } else null

    ModalBottomSheet(onDismissRequest = onDismiss, sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)) {
        Column(
            Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 24.dp)
                .padding(bottom = 24.dp),
        ) {
            Text("Export", style = MaterialTheme.typography.titleLarge)
            Spacer(Modifier.height(16.dp))
            Text("Export as", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                ExportTarget.entries.forEachIndexed { index, option ->
                    SegmentedButton(
                        selected = target == option,
                        onClick = { target = option },
                        enabled = option != ExportTarget.HYPEROS || hasThemeManager,
                        shape = SegmentedButtonDefaults.itemShape(index, ExportTarget.entries.size),
                    ) { Text(if (option == ExportTarget.HYPEROS) "HyperOS theme" else "Icon pack") }
                }
            }
            if (!hasThemeManager) Hint("HyperOS themes need HyperOS Theme Manager.", Modifier.padding(top = 6.dp))
            Spacer(Modifier.height(16.dp))
            OutlinedTextField(
                value = if (pack) packName else name,
                onValueChange = { if (pack) packName = it else name = it },
                label = { Text(if (pack) "Pack name" else "Theme name") },
                supportingText = { Text(if (pack) "Shown in your launcher's icon pack list" else "\"· Light\" or \"· Dark\" is added") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            when (warning) {
                is PackNameWarning.Replaces -> Callout(
                    buildString {
                        append("You already exported a pack named \"${packName.trim()}\"")
                        warning.exportedAt?.let { append(" on ").append(DateFormat.getDateInstance(DateFormat.MEDIUM).format(Date(it))) }
                        append(". Installing this one replaces it. Use another name to keep both.")
                    },
                )
                PackNameWarning.Conflicts -> Callout(
                    "A pack with this name is installed, but it was made before HyperIcon was reinstalled, so Android won't replace it. Uninstall it first, or use another name.",
                )
                null -> Unit
            }
            Spacer(Modifier.height(8.dp))
            if (pack) {
                Text("Icon style", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    listOf(IconStyle.LIGHT, IconStyle.DARK).forEachIndexed { index, style ->
                        SegmentedButton(
                            selected = packStyle == style,
                            onClick = {
                                if (packName == suggestedPackName(defaults.name, packStyle)) packName = suggestedPackName(defaults.name, style)
                                packStyle = style
                            },
                            shape = SegmentedButtonDefaults.itemShape(index, 2),
                        ) { Text(if (style == IconStyle.LIGHT) "Light" else "Dark") }
                    }
                }
                Hint("Every icon keeps this style in light and dark mode, like a HyperOS theme. Edited apps keep their own base icon.", Modifier.padding(top = 6.dp))
            } else {
                Text("Icon style", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    StyleChoice.entries.forEachIndexed { index, option ->
                        SegmentedButton(
                            selected = choice == option,
                            onClick = { choice = option },
                            shape = SegmentedButtonDefaults.itemShape(index, StyleChoice.entries.size),
                        ) { Text(option.label) }
                    }
                }
                if (choice == StyleChoice.BOTH) {
                    Callout(
                        "HyperOS themes can't follow dark mode. HyperIcon creates two themes, Light and Dark: apply the one that matches your mode, and the other one when you switch.",
                    )
                }
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text("Include generated icons", style = MaterialTheme.typography.bodyLarge)
                    Hint("Off: apps without their own monochrome icon keep their original icon.")
                }
                Spacer(Modifier.width(12.dp))
                Switch(checked = includeGenerated, onCheckedChange = { includeGenerated = it })
            }
            Spacer(Modifier.height(20.dp))
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                TextButton(onClick = onDismiss) { Text("Cancel") }
                Spacer(Modifier.width(8.dp))
                Button(onClick = {
                    onExport(ExportOptions(if (pack) packName else name, if (pack) setOf(packStyle) else choice.styles, includeGenerated, target))
                }) { Text("Export") }
            }
        }
    }
}

/** The icon pack's suggested label, e.g. "HyperIcon · Primary · Dark". */
private fun suggestedPackName(name: String, style: IconStyle) = "$name · ${if (style == IconStyle.DARK) "Dark" else "Light"}"

@Composable
private fun Hint(text: String, modifier: Modifier = Modifier) {
    Text(text, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = modifier)
}

/** A tonal card with a warning sign, for things that shouldn't be missed. */
@Composable
private fun Callout(text: String) {
    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer),
        modifier = Modifier.fillMaxWidth().padding(top = 8.dp).semantics { contentDescription = "Warning: $text" },
    ) {
        Row(Modifier.padding(12.dp)) {
            Text("⚠", color = MaterialTheme.colorScheme.onTertiaryContainer, modifier = Modifier.padding(end = 10.dp))
            Text(text, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onTertiaryContainer)
        }
    }
}

/** Progress, result and error UI for exports. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportDialogs(
    state: ExportState,
    onCancel: () -> Unit,
    onDismiss: () -> Unit,
    onSaveCopy: (ExportedFile, String, (Boolean) -> Unit) -> Unit,
    /** Apply icons was started for this file (it becomes the Reapply target). */
    onApplied: (ExportedFile) -> Unit = {},
    /** Hides the progress dialog; the export continues with its notification. */
    onHide: () -> Unit = {},
    dialogHidden: Boolean = false,
) {
    val context = LocalContext.current
    var saving by remember { mutableStateOf<ExportedFile?>(null) }
    // The MIME type only suggests an extension; the file name decides it.
    val saveAs = rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument(DownloadsSaver.MIME_TYPE)) { uri ->
        val file = saving
        saving = null
        if (uri != null && file != null) {
            onSaveCopy(file, uri.toString()) { ok ->
                Toast.makeText(context, if (ok) "Saved" else "Couldn't save the file", Toast.LENGTH_SHORT).show()
            }
        }
    }

    when (state) {
        ExportState.Idle -> Unit
        is ExportState.Running -> if (!dialogHidden) {
            val pack = state.kind == ExportKind.ICON_PACK
            AlertDialog(
                onDismissRequest = {},
                properties = DialogProperties(dismissOnBackPress = false, dismissOnClickOutside = false),
                title = {
                    Text(
                        when {
                            pack -> "Building icon pack"
                            state.files > 1 -> "Exporting theme ${state.file} of ${state.files}"
                            else -> "Exporting theme"
                        },
                    )
                },
                text = {
                    Column {
                        Text(if (state.signing) "Building and signing the APK…" else "Rendering ${state.done} of ${state.total} icons…")
                        Spacer(Modifier.height(12.dp))
                        if (state.signing) {
                            LinearProgressIndicator(modifier = Modifier.fillMaxWidth())
                        } else {
                            LinearProgressIndicator(
                                progress = { if (state.total == 0) 0f else state.done.toFloat() / state.total },
                                modifier = Modifier.fillMaxWidth(),
                            )
                        }
                        Spacer(Modifier.height(12.dp))
                        Hint("You can leave HyperIcon: the export continues, with a notification.")
                    }
                },
                confirmButton = { TextButton(onClick = onHide) { Text("Hide") } },
                dismissButton = { TextButton(onClick = onCancel) { Text("Cancel") } },
            )
        }
        is ExportState.Done -> ModalBottomSheet(onDismissRequest = onDismiss) {
            val pack = state.files.firstOrNull()?.kind == ExportKind.ICON_PACK
            Column(Modifier.fillMaxWidth().padding(horizontal = 24.dp).padding(bottom = 24.dp)) {
                Text(
                    when {
                        pack -> "Icon pack exported"
                        state.files.size > 1 -> "Themes exported"
                        else -> "Theme exported"
                    },
                    style = MaterialTheme.typography.titleLarge,
                )
                Spacer(Modifier.height(4.dp))
                Hint(
                    if (pack) {
                        "Open the APK in your file manager to install it. Android may ask you to allow installs from that app, and HyperOS runs a security scan first."
                    } else {
                        "Apply icons changes only the icons through Theme Manager; your wallpaper and other theme parts stay as they are. This may not work on every HyperOS build."
                    },
                )
                if (pack) {
                    val hint = remember { LauncherHints.forLauncher(LauncherHints.defaultLauncher(context)) }
                    Spacer(Modifier.height(8.dp))
                    Text(hint, style = MaterialTheme.typography.bodyMedium)
                }
                state.files.forEach { file ->
                    Spacer(Modifier.height(12.dp))
                    HorizontalDivider()
                    Spacer(Modifier.height(12.dp))
                    Text(
                        if (file.kind == ExportKind.ICON_PACK) "${file.title} · ${file.iconCount} icons" else "${if (file.style == IconStyle.DARK) "Dark" else "Light"} icons · ${file.iconCount} icons",
                        style = MaterialTheme.typography.titleMedium,
                    )
                    Text(file.location, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        if (file.kind == ExportKind.ICON_PACK) {
                            Button(onClick = {
                                runCatching {
                                    context.startActivity(Intent(DownloadManager.ACTION_VIEW_DOWNLOADS).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
                                }.onFailure { Toast.makeText(context, "No Downloads app found", Toast.LENGTH_SHORT).show() }
                            }) { Text("Open Downloads") }
                        } else {
                            Button(onClick = {
                                if (ThemeApplier.apply(context, file.absolutePath)) {
                                    onApplied(file)
                                } else {
                                    Toast.makeText(context, "Theme Manager isn't available", Toast.LENGTH_SHORT).show()
                                }
                            }) { Text("Apply icons") }
                        }
                        OutlinedButton(onClick = {
                            saving = file
                            saveAs.launch(file.fileName)
                        }) { Text("Save as…") }
                        TextButton(onClick = { context.startActivity(DownloadsSaver.shareIntent(file.uri, file.fileName)) }) { Text("Share") }
                    }
                }
                Spacer(Modifier.height(16.dp))
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                    TextButton(onClick = onDismiss) { Text("Done") }
                }
            }
        }
        is ExportState.Failed -> AlertDialog(
            onDismissRequest = onDismiss,
            title = { Text(if (state.kind == ExportKind.ICON_PACK) "Icon pack failed" else "Export failed") },
            text = { Text(state.message) },
            confirmButton = { TextButton(onClick = onDismiss) { Text("OK") } },
        )
    }
}
