package dev.abhay.monopack.ui

import androidx.annotation.StringRes
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import dev.abhay.monopack.R
import dev.abhay.monopack.iconpack.PackNaming
import dev.abhay.monopack.library.PackNameWarning
import dev.abhay.monopack.model.IconStyle
import java.text.DateFormat
import java.util.Date

/** Icon pack styles: light and dark icons that follow dark mode (default), or one style for both. */
// The suffix is part of the pack's name (its identity), so it isn't translated.
private enum class PackStyleChoice(@StringRes val label: Int, val styles: Set<IconStyle>, val suffix: String?) {
    AUTO(R.string.export_style_auto, setOf(IconStyle.LIGHT, IconStyle.DARK), null),
    LIGHT(R.string.export_style_light, setOf(IconStyle.LIGHT), "Light"),
    DARK(R.string.export_style_dark, setOf(IconStyle.DARK), "Dark"),
}

private enum class StyleChoice(@StringRes val label: Int, val styles: Set<IconStyle>) {
    LIGHT(R.string.export_style_light, setOf(IconStyle.LIGHT)),
    DARK(R.string.export_style_dark, setOf(IconStyle.DARK)),
    BOTH(R.string.export_style_both, setOf(IconStyle.LIGHT, IconStyle.DARK)),
}

/**
 * Export options: the target (HyperOS theme or icon pack), the name, the theme's icon style(s)
 * and whether generated icons are included.
 *
 * @param hasThemeManager without Theme Manager the HyperOS option is disabled.
 * @param packNameWarning what to warn about for an icon-pack name (a pack with that name in the library, or installed).
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportOptionsSheet(
    defaults: ExportOptions,
    onExport: (ExportOptions) -> Unit,
    onDismiss: () -> Unit,
    hasThemeManager: Boolean = true,
    packNameWarning: (String) -> PackNameWarning? = { null },
) {
    var target by rememberSaveable { mutableStateOf(if (hasThemeManager || defaults.target != ExportTarget.HYPEROS) defaults.target else ExportTarget.ICON_PACK) }
    var name by rememberSaveable { mutableStateOf(defaults.name) }
    var choice by rememberSaveable {
        mutableStateOf(if (defaults.styles == setOf(IconStyle.DARK)) StyleChoice.DARK else StyleChoice.LIGHT)
    }
    // An icon pack has one style for every icon (no "Both"), and its full label is editable: it
    // starts as "<name> · Light/Dark" and follows the style while it's still the suggested one.
    var packStyle by rememberSaveable {
        mutableStateOf(PackStyleChoice.entries.firstOrNull { it.styles == defaults.pack?.styles } ?: PackStyleChoice.AUTO)
    }
    // Editing a pack keeps its name, so the new build replaces it.
    var packName by rememberSaveable { mutableStateOf(defaults.pack?.name ?: suggestedPackName(defaults.name, packStyle)) }
    var includeGenerated by rememberSaveable { mutableStateOf(defaults.includeGenerated) }
    val pack = target == ExportTarget.ICON_PACK
    // Keeping the edited pack's name is the point, so it's not warned about.
    val updatingSame = defaults.pack != null && PackNaming.normalize(packName) == PackNaming.normalize(defaults.pack.name)
    val warning = if (pack && !updatingSame) remember(packName) { packNameWarning(packName) } else null

    ModalBottomSheet(onDismissRequest = onDismiss, sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)) {
        Column(
            Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 24.dp)
                .padding(bottom = 24.dp),
        ) {
            Text(if (defaults.pack != null) stringResource(R.string.export_title_update) else stringResource(R.string.export_title), style = MaterialTheme.typography.titleLarge)
            Spacer(Modifier.height(16.dp))
            Text(stringResource(R.string.export_as), style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                ExportTarget.entries.forEachIndexed { index, option ->
                    SegmentedButton(
                        selected = target == option,
                        onClick = { target = option },
                        enabled = option != ExportTarget.HYPEROS || hasThemeManager,
                        shape = SegmentedButtonDefaults.itemShape(index, ExportTarget.entries.size),
                    ) { Text(if (option == ExportTarget.HYPEROS) stringResource(R.string.export_target_theme) else stringResource(R.string.export_target_pack)) }
                }
            }
            if (!hasThemeManager) Hint(stringResource(R.string.export_needs_theme_manager), Modifier.padding(top = 6.dp))
            Spacer(Modifier.height(16.dp))
            OutlinedTextField(
                value = if (pack) packName else name,
                onValueChange = { if (pack) packName = it else name = it },
                label = { Text(if (pack) stringResource(R.string.export_pack_name) else stringResource(R.string.export_theme_name)) },
                supportingText = { Text(if (pack) stringResource(R.string.export_pack_name_hint) else stringResource(R.string.export_theme_name_hint)) },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            when (warning) {
                is PackNameWarning.Replaces -> Callout(
                    if (warning.exportedAt != null) {
                        stringResource(
                            R.string.export_warning_in_library,
                            packName.trim(),
                            DateFormat.getDateInstance(DateFormat.MEDIUM).format(Date(warning.exportedAt)),
                        )
                    } else {
                        stringResource(R.string.export_warning_installed, packName.trim())
                    },
                )
                PackNameWarning.Conflicts -> Callout(
                    stringResource(R.string.export_warning_conflict),
                )
                null -> Unit
            }
            Spacer(Modifier.height(8.dp))
            if (pack) {
                Text(stringResource(R.string.export_icon_style), style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    PackStyleChoice.entries.forEachIndexed { index, option ->
                        SegmentedButton(
                            selected = packStyle == option,
                            onClick = {
                                if (packName == suggestedPackName(defaults.name, packStyle)) packName = suggestedPackName(defaults.name, option)
                                packStyle = option
                            },
                            shape = SegmentedButtonDefaults.itemShape(index, PackStyleChoice.entries.size),
                        ) { Text(stringResource(option.label)) }
                    }
                }
                Hint(
                    if (packStyle == PackStyleChoice.AUTO) {
                        stringResource(R.string.export_style_auto_hint)
                    } else {
                        stringResource(R.string.export_style_single_hint)
                    },
                    Modifier.padding(top = 6.dp),
                )
            } else {
                Text(stringResource(R.string.export_icon_style), style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    StyleChoice.entries.forEachIndexed { index, option ->
                        SegmentedButton(
                            selected = choice == option,
                            onClick = { choice = option },
                            shape = SegmentedButtonDefaults.itemShape(index, StyleChoice.entries.size),
                        ) { Text(stringResource(option.label)) }
                    }
                }
                Hint(stringResource(R.string.hyperos_reset_note), Modifier.padding(top = 8.dp))
                if (choice == StyleChoice.BOTH) {
                    Callout(
                        stringResource(R.string.export_both_themes),
                    )
                }
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text(stringResource(R.string.export_include_generated), style = MaterialTheme.typography.bodyLarge)
                    Hint(stringResource(R.string.export_include_generated_hint))
                }
                Spacer(Modifier.width(12.dp))
                Switch(checked = includeGenerated, onCheckedChange = { includeGenerated = it })
            }
            Spacer(Modifier.height(20.dp))
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                TextButton(onClick = onDismiss) { Text(stringResource(R.string.action_cancel)) }
                Spacer(Modifier.width(8.dp))
                Button(onClick = {
                    onExport(ExportOptions(if (pack) packName else name, if (pack) packStyle.styles else choice.styles, includeGenerated, target))
                }) { Text(if (pack && updatingSame) stringResource(R.string.action_update) else stringResource(R.string.export_title)) }
            }
        }
    }
}

/** The icon pack's suggested label, e.g. "Monopack" or "Monopack · Blue · Dark". */
private fun suggestedPackName(name: String, style: PackStyleChoice) = style.suffix?.let { "$name · $it" } ?: name

@Composable
internal fun Hint(text: String, modifier: Modifier = Modifier) {
    Text(text, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = modifier)
}

/** A tonal card with a warning sign, for things that shouldn't be missed. */
@Composable
internal fun Callout(text: String) {
    val description = stringResource(R.string.callout_warning, text)
    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer),
        modifier = Modifier.fillMaxWidth().padding(top = 8.dp).semantics { contentDescription = description },
    ) {
        Row(Modifier.padding(12.dp)) {
            Text("⚠", color = MaterialTheme.colorScheme.onTertiaryContainer, modifier = Modifier.padding(end = 10.dp))
            Text(text, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onTertiaryContainer)
        }
    }
}
