package dev.abhay.monopack.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import dev.abhay.monopack.hyperos.HYPEROS_RESET_NOTE
import dev.abhay.monopack.library.PackNameWarning
import dev.abhay.monopack.model.IconStyle
import java.text.DateFormat
import java.util.Date

/** Icon pack styles: light and dark icons that follow dark mode (default), or one style for both. */
private enum class PackStyleChoice(val label: String, val styles: Set<IconStyle>, val suffix: String?) {
    AUTO("Light & Dark", setOf(IconStyle.LIGHT, IconStyle.DARK), null),
    LIGHT("Light", setOf(IconStyle.LIGHT), "Light"),
    DARK("Dark", setOf(IconStyle.DARK), "Dark"),
}

private enum class StyleChoice(val label: String, val styles: Set<IconStyle>) {
    LIGHT("Light", setOf(IconStyle.LIGHT)),
    DARK("Dark", setOf(IconStyle.DARK)),
    BOTH("Both", setOf(IconStyle.LIGHT, IconStyle.DARK)),
}

/**
 * Export options: the target (HyperOS theme or icon pack), the name, the theme's icon style(s)
 * and whether generated icons are included.
 *
 * @param hasThemeManager without Theme Manager the HyperOS option is disabled.
 * @param packNameWarning what to warn about for an icon-pack name (a pack with that name in the library, or installed).
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ExportOptionsSheet(
    defaults: ExportOptions,
    onExport: (ExportOptions) -> Unit,
    onDismiss: () -> Unit,
    hasThemeManager: Boolean = true,
    packNameWarning: (String) -> PackNameWarning? = { null },
) {
    var target by rememberSaveable { mutableStateOf(if (hasThemeManager || defaults.target != ExportTarget.HYPEROS) defaults.target else ExportTarget.ICON_PACK) }
    var name by rememberSaveable { mutableStateOf(defaults.name) }
    var choice by rememberSaveable {
        mutableStateOf(if (defaults.styles == setOf(IconStyle.DARK)) StyleChoice.DARK else StyleChoice.LIGHT)
    }
    // An icon pack has one style for every icon (no "Both"), and its full label is editable: it
    // starts as "<name> · Light/Dark" and follows the style while it's still the suggested one.
    var packStyle by rememberSaveable { mutableStateOf(PackStyleChoice.AUTO) }
    var packName by rememberSaveable { mutableStateOf(suggestedPackName(defaults.name, packStyle)) }
    var includeGenerated by rememberSaveable { mutableStateOf(defaults.includeGenerated) }
    val pack = target == ExportTarget.ICON_PACK
    val warning = if (pack) remember(packName) { packNameWarning(packName) } else null

    ModalBottomSheet(onDismissRequest = onDismiss, sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)) {
        Column(
            Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 24.dp)
                .padding(bottom = 24.dp),
        ) {
            Text("Export", style = MaterialTheme.typography.titleLarge)
            Spacer(Modifier.height(16.dp))
            Text("Export as", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                ExportTarget.entries.forEachIndexed { index, option ->
                    SegmentedButton(
                        selected = target == option,
                        onClick = { target = option },
                        enabled = option != ExportTarget.HYPEROS || hasThemeManager,
                        shape = SegmentedButtonDefaults.itemShape(index, ExportTarget.entries.size),
                    ) { Text(if (option == ExportTarget.HYPEROS) "HyperOS theme" else "Icon pack") }
                }
            }
            if (!hasThemeManager) Hint("HyperOS themes need HyperOS Theme Manager.", Modifier.padding(top = 6.dp))
            Spacer(Modifier.height(16.dp))
            OutlinedTextField(
                value = if (pack) packName else name,
                onValueChange = { if (pack) packName = it else name = it },
                label = { Text(if (pack) "Pack name" else "Theme name") },
                supportingText = { Text(if (pack) "Shown in your launcher's icon pack list" else "\"· Light\" or \"· Dark\" is added") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            when (warning) {
                is PackNameWarning.Replaces -> Callout(
                    buildString {
                        if (warning.exportedAt != null) {
                            append("Your library has a pack named \"${packName.trim()}\" (exported ")
                            append(DateFormat.getDateInstance(DateFormat.MEDIUM).format(Date(warning.exportedAt)))
                            append(")")
                        } else {
                            append("A pack named \"${packName.trim()}\" is installed")
                        }
                        append(". Installing this one replaces it. Use another name to keep both.")
                    },
                )
                PackNameWarning.Conflicts -> Callout(
                    "A pack with this name is installed, but it was made before Monopack was reinstalled, so Android won't replace it. Uninstall it first, or use another name.",
                )
                null -> Unit
            }
            Spacer(Modifier.height(8.dp))
            if (pack) {
                Text("Icon style", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    PackStyleChoice.entries.forEachIndexed { index, option ->
                        SegmentedButton(
                            selected = packStyle == option,
                            onClick = {
                                if (packName == suggestedPackName(defaults.name, packStyle)) packName = suggestedPackName(defaults.name, option)
                                packStyle = option
                            },
                            shape = SegmentedButtonDefaults.itemShape(index, PackStyleChoice.entries.size),
                        ) { Text(option.label) }
                    }
                }
                Hint(
                    if (packStyle == PackStyleChoice.AUTO) {
                        "Light icons in light mode and dark icons in dark mode; your launcher switches them (some need a restart). Edited apps with auto night mode off keep one icon."
                    } else {
                        "Every icon keeps this style in light and dark mode."
                    },
                    Modifier.padding(top = 6.dp),
                )
            } else {
                Text("Icon style", style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(bottom = 6.dp))
                SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                    StyleChoice.entries.forEachIndexed { index, option ->
                        SegmentedButton(
                            selected = choice == option,
                            onClick = { choice = option },
                            shape = SegmentedButtonDefaults.itemShape(index, StyleChoice.entries.size),
                        ) { Text(option.label) }
                    }
                }
                Hint(HYPEROS_RESET_NOTE, Modifier.padding(top = 8.dp))
                if (choice == StyleChoice.BOTH) {
                    Callout(
                        "HyperOS themes can't follow dark mode. Monopack creates two themes, Light and Dark: apply the one that matches your mode, and the other one when you switch.",
                    )
                }
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text("Include generated icons", style = MaterialTheme.typography.bodyLarge)
                    Hint("Off: apps without their own monochrome icon keep their original icon.")
                }
                Spacer(Modifier.width(12.dp))
                Switch(checked = includeGenerated, onCheckedChange = { includeGenerated = it })
            }
            Spacer(Modifier.height(20.dp))
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                TextButton(onClick = onDismiss) { Text("Cancel") }
                Spacer(Modifier.width(8.dp))
                Button(onClick = {
                    onExport(ExportOptions(if (pack) packName else name, if (pack) packStyle.styles else choice.styles, includeGenerated, target))
                }) { Text("Export") }
            }
        }
    }
}

/** The icon pack's suggested label, e.g. "Monopack · Primary" or "Monopack · Primary · Dark". */
private fun suggestedPackName(name: String, style: PackStyleChoice) = style.suffix?.let { "$name · $it" } ?: name

@Composable
internal fun Hint(text: String, modifier: Modifier = Modifier) {
    Text(text, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = modifier)
}

/** A tonal card with a warning sign, for things that shouldn't be missed. */
@Composable
internal fun Callout(text: String) {
    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer),
        modifier = Modifier.fillMaxWidth().padding(top = 8.dp).semantics { contentDescription = "Warning: $text" },
    ) {
        Row(Modifier.padding(12.dp)) {
            Text("⚠", color = MaterialTheme.colorScheme.onTertiaryContainer, modifier = Modifier.padding(end = 10.dp))
            Text(text, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onTertiaryContainer)
        }
    }
}
